### PR TITLE
Add optional filter for unsupported method consume

### LINKED ISSUE #78: APIs with form 'consumes' don't generate valid client code, suggesting an optional filter
Currently generator works fine except when an API accepts form data, for example for a file upload. The generated code causes a compile error due to a bad template.

I checked the issues and looks like there's a rewrite in the works, so I added an optional command line argument to skip generating those particular methods instead, which is 100% backwards compatible. Please check my PR

### PR DESCRIPTION
**Pull request by jalmeida-mct**
closes #78

### CODE REVIEW

**Comment by vmasek** [comment]
Hello, thank you for the PR :+1:

Please revert the `package-lock.json` and sign the CLA so it can be merged :shipit:

**Comment by jalmeida-mct** [comment]
Hi, thanks for the quick reply! Sorry for the late response, just pushed the revert. I've also signed the CLA, but maybe I need to fork it from my personal account for it to work?

**Comment by vmasek** [comment]
@jalmeida-mct there are still changes for both of `package-lock.json` and you also bumped a version in `package.json` please revert these changes, I'll do them with release

**Comment by jalmeida-mct** [comment]
my bad, rebased the whole thing into a single commit

**Comment by vmasek** [comment]
@jalmeida-mct It tells me that CLA is still not signed, what did you mean by forking it to your personal acc?

It should work in a way that you just click on CLA check in this PR, it redirects you to the CLA bot and then you get redirected back after you agree with terms

**Comment by jalmeida-mct** [comment]
I mean this is what I see on the CLA page: https://imgur.com/a/v6nfZeq
I've definitely hit sign but it doesn't seem to update?

**Pull request closed without merging**
