### PR TITLE
fix(template) make module template angular 10 compatible (closes #93)

### LINKED ISSUE #93: Incompatible with Angular 10
The api client module generated needs a small fix in the template to support Angular 10, ie a change from

```typescript
  static forRoot(config: APIClientModuleConfig = {}): ModuleWithProviders {
```

to 

```typescript
  static forRoot(config: APIClientModuleConfig = {}): ModuleWithProviders<APIClientModule> {
```

I'm opening a PR shortly to fix that.

### PR DESCRIPTION
**Pull request by Azuka**
closes #93

### CODE REVIEW

**Comment by vmasek** [comment]
Could you please have a look if you agreed with CLA (clabot handles that), it is needed in order to merge the PR, other than that this has no issues and may be merged :shipit:

**Comment by Azuka** [comment]
@vmasek how do I do that?

**Comment by vmasek** [comment]
I'll have a look

**Comment by vmasek** [comment]
I was just stuck.

Did you also test the backward compatibility? I need to make sure it will work for "lower" versions or release this as a mayor version.

**Comment by Azuka** [comment]
@vmasek, I believe the `test-angular-project` uses Angular 9, so it should work. I'm not sure about 8.

**Pull request merged**
