### PR TITLE
 new options --apiName & --skipModule

### PR DESCRIPTION
**Pull request by admir86**
added new options.

 **`-n, --apiName`**
possibility to use only a subset of the swagger definitions as input for the generator. For this I use the operationId field to filter the definitions (filter by operationId works for me but perhaps is better to filter by tag?)
with this options only needed models will be generated and the angular service gets the name of the apiName parameter.

example:
```
"paths": {
		"/api/dummyselector/{organizerTaskElementId}": {
			"get": {
				"tags": [
					"DummySelector"
				],
				"operationId": "DummySelector_Get",
				"consumes": [],
				"produces": [
                                         ...
				],
				"parameters": [
					{
                                          ...
					}
				],
				"responses": {
                                        ...
				}
			}
		},
                ...
}
```
calling api-client-generator with -n DummySelector will fetch all paths where operationId starts with DummySelector

 **`-m, --skipModule`**
if you don't need the module, you can use this option to skip creating the index file with the module export

### CODE REVIEW

**Comment by vmasek** [comment]
@admir86 Thank you for your PR 👍 I'll try to review it soon.

I noticed there are some code format changes which shouldn't be included in PR.

**Comment by admir86** [comment]
@vmasek ok thx.
the code format changes are probably from vs code (format on save) sorry for that.

By the way, the tests are broken since the swagger file validation step.

**Comment by vmasek** [comment]
Preferably I would pick tags for splitting API client to multiple services as it is much more explicit.

@admir86 so with this PR you will be able to create (generate) one API service at the time (based on the tag name), I think it would be best to extend it so you will be able to specify which tags should be generated as a list.

- If one of the tags is not found, they should be skipped but also write a warning about the missing tag.
- Test should include generating an API services form multiple tags with one or few paths skipped due to different tag thats not mentioned in user provided list.
- Parameter name 'apiName' should be changed to something more semanticali correct, for example `splitPathTags` (feel free to come up with something better :smile: )


One more think is, the skip module option is because of services being part of the module and you want to provide them separateli in modules where you use them?

**Comment by admir86** [comment]
@vmasek thx for your feedback.

> I think it would be best to extend it so you will be able to specify which tags should be generated as a list.

would you create for each tag/api a separate file/service or should the behavior be same, like without this `splitPathTags` option (all apis in same file)

> Parameter name 'apiName' should be changed to something more semantically correct, for example, splitPathTags (feel free to come up with something better 😄 )

I was inspired by the [selective generation option from swagger-codegen](https://github.com/swagger-api/swagger-codegen#selective-generation) but the name `splitPathTags` is ok :)

> One more thing is, the skip module option is because of services being part of the module and you want to provide them separately in modules where you use them?

yes that's correct

**Comment by vmasek** [comment]
@admir86 
It would create separate service for each tag.

Also, it could support generating all tag+service options, if some special value is used (`all`) or if the flag is used with no parameter?

**Comment by admir86** [comment]
ok I'll try :) maybe tomorrow or next days...

**Comment by admir86** [comment]
now better? 
feel free to make some code refactoring :)

**Comment by admir86** [comment]
@vmasek thx!

**Comment by vmasek** [comment]
Thank you for your collaboration :) I was planning to as such a functionality but didn't get to it in time :smile: 

Now tests are the priority, later I will probably be extending it more.

**Pull request merged**
